//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nano_Tech.Models
{   
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.orders = new HashSet<order>();
        }
    
        public int userid { get; set; }
        [Required(ErrorMessage ="Required")]
        public string username { get; set; }
        [Required(ErrorMessage = "Required")]
        [DataType(DataType.Password)]
        public string userpass { get; set; }
        [Required(ErrorMessage = "Required")]
        [MinLength(11,ErrorMessage ="Minimum length 11 digits")]
        public string usercontact { get; set; }
        [Required(ErrorMessage = "Enter valid email")]
        [DataType(DataType.EmailAddress)]
        public string useremail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order> orders { get; set; }
    }
}
